os: linux
dist: trusty
before_install:
    - sudo apt-get update -qq
    - sudo apt-get --no-install-recommends install -y ack-grep cpanminus findutils libperl-dev make perl
    - sudo dpkg-divert --local --divert /usr/bin/ack --rename --add /usr/bin/ack-grep
install:
    - sudo cpanm Alien::Tidyp
    - sudo cpanm --notest HTML::Tidy
    - sudo cpanm File::Copy File::Find::Object File::Find::Object::Rule File::Path File::Spec  HTML::TokeParser IO::All Template Test::HTML::Recursive::DeprecatedTags Test::HTML::Tidy::Recursive Test::HTML::Tidy::Recursive::Strict Test::More Test::TrailingSpace
script: "cd www.linux.org.il-new-site/template-toolkit/ && ./gen-helpers && make && make test"
